<a href="https://colab.research.google.com/github/BarshaPanthi7/Danphe_task_Barsha/blob/main/notebooks/03_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

iemocap dataset eda

environment setup

In [1]:
import sys
print("Python version:", sys.version)

Python version: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

kaggle api configuration

In [ ]:
from google.colab import files

#uploading the kaggle api key
files.upload()

In [3]:
import os
import shutil

# Creating Kaggle configuration directory
os.makedirs("/root/.config/kaggle", exist_ok=True)

# Moving the API key to the required location
shutil.move(
    "/content/kaggle.json",
    "/root/.config/kaggle/kaggle.json"
)

# Setting secure permissions
os.chmod(
    "/root/.config/kaggle/kaggle.json",
    0o600
)

print("Kaggle API configured successfully.")

Kaggle API configured successfully.

upgrading kaggle cli

In [4]:
!pip install -q --upgrade kaggle

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.2/126.2 kB 4.7 MB/s eta 0:00:00

In [5]:
!kaggle --version

Kaggle CLI 2.2.4

searching for iemocap in kaggle

In [ ]:
from google.colab import userdata

KAGGLE_API_TOKEN = userdata.get("KAGGLE_API_TOKEN")

print("Kaggle token loaded:", bool(KAGGLE_API_TOKEN))

In [7]:
import os

os.environ["KAGGLE_API_TOKEN"] = KAGGLE_API_TOKEN

In [8]:
!kaggle datasets list -s iemocap

ref                                                       title                                                     size  lastUpdated                 downloadCount  voteCount  usabilityRating
--------------------------------------------------------  -------------------------------------------------  -----------  --------------------------  -------------  ---------  ---------------
columbine/iemocap                                         IEMOCAP                                               10116183  2020-12-17 01:45:18.677000           3366         34  0.875
dejolilandry/iemocapfullrelease                           Iemocap-full-release                               12384401065  2022-01-01 14:28:10.087000           6685         35  0.375
samuelsamsudinng/iemocap-emotion-speech-database          IEMOCAP Emotion Speech Database                          36658  2020-12-14 14:16:54.373000           5601         31  0.47058824
mouadriali/iemocap-transcriptions-english-french          IEMOCAP - Transcriptions (English, French)/Audio    6205191410  2022-05-09 07:55:22.570000            957         20  0.64705884
sangayb/iemocap                                           iemocap                                             1070691734  2023-03-07 18:09:32.243000           1450          6  0.5
jiten597/iemocap                                          IEMOCAP                                            17838586906  2023-06-06 23:58:02.833000            655          5  0.5625
flarescen/iemocap-audios                                  IEMOCAP Audios                                      1048776372  2024-11-11 14:50:48.020000            190          2  0.5
jamaliasultanajisha/iemocap-full                          iemocap_full                                       12415361977  2020-09-19 14:41:44.527000            984         10  0.25
tsqmsds2023fastnulhr/iemocap-frill                        IEMOCAP FRILL                                       1346661576  2024-11-04 12:06:01.887000             14          0  0.7647059
netgvarun2005/preprocessedaugmentedemotionsspeechdataset  PreprocessedAugmentedEmotionsSpeechDataset           831861615  2023-12-04 08:58:21.707000             72          4  0.625
ktgiahieu/iemocap-trained-weights                         [IEMOCAP] Trained weights                           8171716805  2023-12-22 00:17:09.633000              6          1  0.4375
saifeldenmohamed8/iemocapreduced                          iemocapreduced                                     12414793442  2025-12-24 17:37:51.687000              2          1  0.3125
mohammadaamirrayyan/iemocap                               iemocap                                             1083321312  2025-04-05 08:27:31.663000              7          0  0.1875
joykiratsingh18/iemocap                                   IEMOCAP                                              251771308  2022-04-28 20:47:36.313000             29          1  0.0
mdnabilsadique/iemocap                                    IEMOCAP                                             3513627812  2024-12-07 16:55:21.647000             10          0  0.0625
ourbucket/iemocap-audio-complete                          IEMOCAP Complete Audio Dataset                      1070196144  2026-02-16 06:10:26.503000            144          0  0.64705884
utkmal/tensor-representations-of-speech-emotion-datasets  Tensor Representations of Speech Emotion Datasets   7421162393  2025-06-18 16:07:01.530000             33          1  0.5294118
quanghuy225/iemocap                                       iemocap                                                3280264  2026-07-13 08:39:35.577000              2          0  0.23529412
yashrajpoddar/iemocap-dataset-no-videos                   IEMOCAP Dataset no videos                          12414793442  2024-09-23 08:35:12.130000             15          1  0.1875
farneetsingh/complete-iemocap-parsed                      Complete IEMOCAP Parsed                                1399937  2024-04-20 15:44:34.230000             30          0  0.29411766

In [9]:
!kaggle datasets files -d dejolilandry/iemocapfullrelease --page-size 200

Next Page Token = CfDJ8GNxPX3qpaJEpxfoBSRBZPcDUnXD8UUJVXAD3-yC6BDM1z4IhiDkiiMNIdXWJkECRtMyd7vTQ95yS7Jfv6fdDGoV-RIP_JHRGEfSnLZMvFXN3LnN52TH44R6-bOAea3SA7no8EumJ0fFzG7RQDWDeth-BB9QAiUgJ2UHhfeOCaC37mregz3QNnVTp5f5LF7_RLx5Qgl8ygYpVNlJc1ofpKgpZfviS96nHLN5JW1KU7QXDAA
name                                                                                            size  creationDate
-------------------------------------------------------------------------------------------  -------  --------------------------
IEMOCAP_full_release/Documentation/FIVE_face_markers2.png                                     437923  2022-01-01 14:32:08.773000
IEMOCAP_full_release/Documentation/HumaineInfo.txt                                               555  2022-01-01 14:32:08.917000
IEMOCAP_full_release/Documentation/corpus.dic                                                6696895  2022-01-01 14:32:08.895000
IEMOCAP_full_release/Documentation/phonemes.txt                                                 1121  2022-01-01 14:32:08.929000
IEMOCAP_full_release/Documentation/timeinfo.txt                                                  206  2022-01-01 14:32:08.716000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro01_e3.anvil            9012  2022-01-01 14:32:30.607000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro01_e3_atr.txt          1410  2022-01-01 14:32:30.607000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro01_e4.anvil           11505  2022-01-01 14:32:30.628000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro01_e4_atr.txt          2373  2022-01-01 14:32:30.607000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro02_e3.anvil           11327  2022-01-01 14:32:30.652000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro02_e3_atr.txt          1786  2022-01-01 14:32:30.618000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro02_e4.anvil           14114  2022-01-01 14:32:30.639000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro02_e4_atr.txt          2635  2022-01-01 14:32:30.618000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro03_e1.anvil           15317  2022-01-01 14:32:30.618000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro03_e1_atr.txt          2444  2022-01-01 14:32:30.618000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro03_e2.anvil           15233  2022-01-01 14:32:30.607000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro03_e2_atr.txt          2444  2022-01-01 14:32:30.607000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro03_e3.anvil           15233  2022-01-01 14:32:30.607000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro03_e3_atr.txt          2444  2022-01-01 14:32:30.652000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro04_e1.anvil           20736  2022-01-01 14:32:30.618000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro04_e1_atr.txt          3337  2022-01-01 14:32:30.608000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro04_e2.anvil           20736  2022-01-01 14:32:30.652000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro04_e2_atr.txt          3337  2022-01-01 14:32:30.618000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro05_e3.anvil           19520  2022-01-01 14:32:30.596000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro05_e3_atr.txt          3149  2022-01-01 14:32:30.652000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro05_e4.anvil           25036  2022-01-01 14:32:30.618000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro05_e4_atr.txt          5246  2022-01-01 14:32:30.607000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro06_e1.anvil           13909  2022-01-01 14:32:30.618000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro06_e1_atr.txt          2209  2022-01-01 14:32:30.686000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro06_e2.anvil           13909  2022-01-01 14:32:30.608000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro06_e2_atr.txt          2209  2022-01-01 14:32:30.717000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro07_e1.anvil           11013  2022-01-01 14:32:30.618000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro07_e1_atr.txt          1739  2022-01-01 14:32:30.628000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro07_e2.anvil           11013  2022-01-01 14:32:30.607000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_impro07_e2_atr.txt          1739  2022-01-01 14:32:30.618000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script01_1_e1.anvil        26165  2022-01-01 14:32:30.628000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script01_1_e1_atr.txt       4450  2022-01-01 14:32:30.664000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script01_1_e2.anvil        26165  2022-01-01 14:32:30.639000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script01_1_e2_atr.txt       4450  2022-01-01 14:32:30.685000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script01_1_e3.anvil        26034  2022-01-01 14:32:30.706000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script01_1_e3_atr.txt       4450  2022-01-01 14:32:30.674000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script01_2_e1.anvil         9856  2022-01-01 14:32:30.717000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script01_2_e1_atr.txt       1650  2022-01-01 14:32:30.686000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script01_2_e2.anvil         9856  2022-01-01 14:32:30.674000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script01_2_e2_atr.txt       1650  2022-01-01 14:32:30.728000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script01_3_e1.anvil        22088  2022-01-01 14:32:30.685000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script01_3_e1_atr.txt       3750  2022-01-01 14:32:30.696000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script01_3_e2.anvil        22088  2022-01-01 14:32:30.696000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script01_3_e2_atr.txt       3750  2022-01-01 14:32:30.706000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script01_3_e3.anvil        21970  2022-01-01 14:32:30.685000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script01_3_e3_atr.txt       3750  2022-01-01 14:32:30.696000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script02_1_e3.anvil        20738  2022-01-01 14:32:30.744000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script02_1_e3_atr.txt       3550  2022-01-01 14:32:30.707000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script02_1_e4.anvil        26410  2022-01-01 14:32:30.696000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script02_1_e4_atr.txt       5599  2022-01-01 14:32:30.685000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script02_2_e3.anvil        28584  2022-01-01 14:32:30.686000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script02_2_e3_atr.txt       4900  2022-01-01 14:32:30.674000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script02_2_e4.anvil        36284  2022-01-01 14:32:30.744000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script02_2_e4_atr.txt       7602  2022-01-01 14:32:30.728000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script03_1_e3.anvil        20731  2022-01-01 14:32:30.706000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script03_1_e3_atr.txt       3550  2022-01-01 14:32:30.706000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script03_1_e4.anvil        25850  2022-01-01 14:32:30.686000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script03_1_e4_atr.txt       5099  2022-01-01 14:32:30.685000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script03_2_e1.anvil        23933  2022-01-01 14:32:30.787000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script03_2_e1_atr.txt       4100  2022-01-01 14:32:30.674000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script03_2_e2.anvil        23933  2022-01-01 14:32:30.707000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01F_script03_2_e2_atr.txt       4100  2022-01-01 14:32:30.696000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro01_e1.anvil           18956  2022-01-01 14:32:30.744000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro01_e1_atr.txt          3055  2022-01-01 14:32:30.707000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro01_e2.anvil           18956  2022-01-01 14:32:30.728000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro01_e2_atr.txt          3055  2022-01-01 14:32:30.706000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro02_e1.anvil           14148  2022-01-01 14:32:30.707000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro02_e1_atr.txt          2256  2022-01-01 14:32:30.696000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro02_e2.anvil           14148  2022-01-01 14:32:30.686000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro02_e2_atr.txt          2256  2022-01-01 14:32:30.717000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro03_e1.anvil           15542  2022-01-01 14:32:30.707000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro03_e1_atr.txt          2491  2022-01-01 14:32:30.696000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro03_e2.anvil           15542  2022-01-01 14:32:30.728000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro03_e2_atr.txt          2491  2022-01-01 14:32:30.728000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro04_e1.anvil           15322  2022-01-01 14:32:30.744000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro04_e1_atr.txt          2444  2022-01-01 14:32:30.707000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro04_e2.anvil           15158  2022-01-01 14:32:30.696000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro04_e2_atr.txt          2397  2022-01-01 14:32:30.696000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro05_e1.anvil           20415  2022-01-01 14:32:30.686000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro05_e1_atr.txt          3290  2022-01-01 14:32:30.717000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro05_e2.anvil           20415  2022-01-01 14:32:30.696000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro05_e2_atr.txt          3290  2022-01-01 14:32:30.696000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro06_e1.anvil           17645  2022-01-01 14:32:30.707000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro06_e1_atr.txt          2820  2022-01-01 14:32:30.777000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro06_e2.anvil           17645  2022-01-01 14:32:30.744000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro06_e2_atr.txt          2820  2022-01-01 14:32:30.777000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro07_e1.anvil           20124  2022-01-01 14:32:30.744000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro07_e1_atr.txt          3243  2022-01-01 14:32:30.754000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro07_e3.anvil           20124  2022-01-01 14:32:30.728000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_impro07_e3_atr.txt          3243  2022-01-01 14:32:30.744000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script01_1_e1.anvil        25570  2022-01-01 14:32:30.755000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script01_1_e1_atr.txt       4350  2022-01-01 14:32:30.744000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script01_1_e2.anvil        25570  2022-01-01 14:32:30.744000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script01_1_e2_atr.txt       4350  2022-01-01 14:32:30.777000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script01_1_e3.anvil        25457  2022-01-01 14:32:30.754000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script01_1_e3_atr.txt       4350  2022-01-01 14:32:30.744000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script01_2_e1.anvil         9889  2022-01-01 14:32:30.798000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script01_2_e1_atr.txt       1650  2022-01-01 14:32:30.766000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script01_2_e2.anvil         9889  2022-01-01 14:32:30.744000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script01_2_e2_atr.txt       1650  2022-01-01 14:32:30.847000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script01_3_e3.anvil        21983  2022-01-01 14:32:30.777000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script01_3_e3_atr.txt       3750  2022-01-01 14:32:30.787000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script01_3_e4.anvil        27474  2022-01-01 14:32:30.755000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script01_3_e4_atr.txt       5415  2022-01-01 14:32:30.798000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script02_1_e1.anvil        21121  2022-01-01 14:32:30.755000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script02_1_e1_atr.txt       3600  2022-01-01 14:32:30.766000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script02_1_e2.anvil        21121  2022-01-01 14:32:30.787000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script02_1_e2_atr.txt       3600  2022-01-01 14:32:30.777000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script02_2_e3.anvil        29417  2022-01-01 14:32:30.777000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script02_2_e3_atr.txt       4950  2022-01-01 14:32:30.787000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script02_2_e4.anvil        38114  2022-01-01 14:32:30.765000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script02_2_e4_atr.txt       7988  2022-01-01 14:32:30.798000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script03_1_e3.anvil        24742  2022-01-01 14:32:30.777000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script03_1_e3_atr.txt       4250  2022-01-01 14:32:30.766000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script03_1_e4.anvil        30467  2022-01-01 14:32:30.765000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script03_1_e4_atr.txt       5993  2022-01-01 14:32:30.810000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script03_2_e1.anvil        25114  2022-01-01 14:32:30.766000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script03_2_e1_atr.txt       4300  2022-01-01 14:32:30.766000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script03_2_e2.anvil        25114  2022-01-01 14:32:30.777000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Attribute/Ses01M_script03_2_e2_atr.txt       4300  2022-01-01 14:32:30.787000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro01_e2.anvil          5838  2022-01-01 14:32:30.798000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro01_e2_cat.txt        1102  2022-01-01 14:32:30.777000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro01_e3.anvil          8667  2022-01-01 14:32:30.777000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro01_e3_cat.txt        1303  2022-01-01 14:32:30.798000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro01_e4.anvil          5830  2022-01-01 14:32:30.787000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro01_e4_cat.txt        1094  2022-01-01 14:32:30.777000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro02_e1.anvil          7235  2022-01-01 14:32:30.777000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro02_e1_cat.txt        1273  2022-01-01 14:32:30.798000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro02_e3.anvil         10298  2022-01-01 14:32:30.820000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro02_e3_cat.txt        1534  2022-01-01 14:32:30.810000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro02_e4.anvil          7329  2022-01-01 14:32:30.890000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro02_e4_cat.txt        1400  2022-01-01 14:32:30.777000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro03_e1.anvil          9785  2022-01-01 14:32:30.810000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro03_e1_cat.txt        1802  2022-01-01 14:32:30.798000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro03_e2.anvil          9707  2022-01-01 14:32:30.798000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro03_e2_cat.txt        1877  2022-01-01 14:32:30.836000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro03_e4.anvil         10298  2022-01-01 14:32:30.809000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro03_e4_cat.txt        2006  2022-01-01 14:32:30.836000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro04_e1.anvil         13364  2022-01-01 14:32:30.820000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro04_e1_cat.txt        2636  2022-01-01 14:32:30.820000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro04_e2.anvil         13141  2022-01-01 14:32:30.847000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro04_e2_cat.txt        2566  2022-01-01 14:32:30.847000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro04_e4.anvil         13425  2022-01-01 14:32:30.847000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro04_e4_cat.txt        2697  2022-01-01 14:32:30.810000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro05_e1.anvil         12297  2022-01-01 14:32:30.820000
IEMOCAP_full_release/Session1/dialog/EmoEvaluation/Categorical/Ses01F_impro05_e1_cat.txt        2298  2022-01-01 14:32:30.836000

In [13]:

import kagglehub
path = kagglehub.dataset_download(
    "dejolilandry/iemocapfullrelease"
)

Download already complete (12384401065 bytes).
Extracting files...

In [14]:
!df -h /content

Filesystem      Size  Used Avail Use% Mounted on
overlay         108G   43G   66G  40% /

In [15]:
import os

print("Dataset path:", path)

print("\nContents of dataset:")

for item in os.listdir(path):
    print(item)

Dataset path: /root/.cache/kagglehub/datasets/dejolilandry/iemocapfullrelease/versions/1

Contents of dataset:
IEMOCAP_full_release

In [16]:
# Defining the main IEMOCAP directory
iemocap_path = os.path.join(path, "IEMOCAP_full_release")

print("IEMOCAP path:", iemocap_path)

print("\nContents of IEMOCAP_full_release:")

for item in os.listdir(iemocap_path):
    print(item)

IEMOCAP path: /root/.cache/kagglehub/datasets/dejolilandry/iemocapfullrelease/versions/1/IEMOCAP_full_release

Contents of IEMOCAP_full_release:
Session5
Documentation
Session1
Session4
Session2
Session3

checking the content of each session

In [17]:
# Checking the contents of each session

sessions = [
    "Session1",
    "Session2",
    "Session3",
    "Session4",
    "Session5"
]

for session in sessions:
    session_path = os.path.join(iemocap_path, session)

    print(f"\n{session}:")
    for item in os.listdir(session_path):
        print("  ", item)

Session1:
   sentences
   dialog

Session2:
   sentences
   dialog

Session3:
   sentences
   dialog

Session4:
   sentences
   dialog

Session5:
   sentences
   dialog

In [18]:
# Inspecting the contents of sentences and dialog for each session

for session in sessions:
    session_path = os.path.join(iemocap_path, session)

    print(f"\n{session}")

    for folder in ["sentences", "dialog"]:
        folder_path = os.path.join(session_path, folder)

        print(f"  {folder}:")
        for item in os.listdir(folder_path):
            print(f"    {item}")

Session1
  sentences:
    MOCAP_head
    ForcedAlignment
    wav
    MOCAP_hand
    MOCAP_rotated
  dialog:
    MOCAP_head
    wav
    transcriptions
    lab
    MOCAP_hand
    EmoEvaluation
    avi
    MOCAP_rotated

Session2
  sentences:
    MOCAP_head
    ForcedAlignment
    wav
    MOCAP_hand
    MOCAP_rotated
  dialog:
    MOCAP_head
    wav
    transcriptions
    lab
    MOCAP_hand
    EmoEvaluation
    MOCAP_rotated

Session3
  sentences:
    MOCAP_head
    ForcedAlignment
    wav
    MOCAP_hand
    MOCAP_rotated
  dialog:
    MOCAP_head
    wav
    transcriptions
    lab
    MOCAP_hand
    EmoEvaluation
    MOCAP_rotated

Session4
  sentences:
    MOCAP_head
    ForcedAlignment
    wav
    MOCAP_hand
    MOCAP_rotated
  dialog:
    MOCAP_head
    wav
    transcriptions
    lab
    MOCAP_hand
    EmoEvaluation
    MOCAP_rotated

Session5
  sentences:
    MOCAP_head
    ForcedAlignment
    wav
    MOCAP_hand
    MOCAP_rotated
  dialog:
    MOCAP_head
    wav
    transcriptions
    lab
    MOCAP_hand
    EmoEvaluation
    MOCAP_rotated

## Exploring Emotion and Transcription Data

Each session contains an `EmoEvaluation` folder and a `transcriptions`
folder inside the `dialog` directory.

`EmoEvaluation` contains emotional annotations, while `transcriptions`
contains the corresponding spoken utterances.

We will first check the number of files available in these folders
across all five sessions.

data profiling

In [33]:
import re
import os
import pandas as pd

emo_records = []

# Regex for EmoEvaluation lines, e.g.:
# [6.2901 - 8.2357]	Ses01F_impro01_F000	neu	[2.5, 2.5, 2.5]
emo_regex = r'\[(\d+\.\d+) - (\d+\.\d+)\]\s+(\S+)\s+(\w+)\s+\[([\d.,\s]+)\]'

for session in sessions:
    emo_path = os.path.join(iemocap_path, session, 'dialog', 'EmoEvaluation')
    if not os.path.exists(emo_path):
        print(f"Warning: EmoEvaluation path not found for {session}")
        continue

    # Only the top-level .txt files here hold the final emotion labels
    # (Categorical/ and Attribute/ subfolders hold raw per-annotator data, skip those)
    for file_name in os.listdir(emo_path):
        file_path = os.path.join(emo_path, file_name)
        if os.path.isfile(file_path) and file_name.endswith('.txt'):
            with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                for line in f:
                    match = re.match(emo_regex, line)
                    if match:
                        start, end, utt_id, emotion, vad = match.groups()
                        valence, arousal, dominance = [float(x) for x in vad.split(',')]
                        emo_records.append({
                            'utterance_id': utt_id,
                            'emotion': emotion,
                            'valence': valence,
                            'arousal': arousal,
                            'dominance': dominance
                        })

emo_df = pd.DataFrame(emo_records)
print("Emotion records parsed:", emo_df.shape)
display(emo_df.head())

# Merge emotion labels into the main transcription DataFrame using utterance_id as key
df = df.drop(columns=['emotion'])  # drop the empty placeholder column
df = df.merge(emo_df, on='utterance_id', how='left')

print("\nFinal merged shape:", df.shape)
display(df.head())

Emotion records parsed: (10039, 5)

          utterance_id emotion  valence  arousal  dominance
0  Ses01M_impro06_F000     neu      3.0      2.5        2.0
1  Ses01M_impro06_F001     neu      3.0      2.0        2.5
2  Ses01M_impro06_F002     neu      3.0      2.0        2.5
3  Ses01M_impro06_F003     sad      2.5      2.0        2.5
4  Ses01M_impro06_F004     sad      2.5      2.0        2.0

Final merged shape: (10087, 11)

,session,file_name,utterance_id,speaker,utterance,start_time,end_time,emotion,valence,arousal,dominance
0,Session1,Ses01M_impro06.txt,Ses01M_impro06_F000,F000,You okay?,10.0955,12.6800,neu,3.0,2.5,2.0
1,Session1,Ses01M_impro06.txt,Ses01M_impro06_M000,M000,"Yeah, I'm just-- yeah",12.4633,16.5100,sad,3.0,2.5,2.0
2,Session1,Ses01M_impro06.txt,Ses01M_impro06_M001,M001,"Just kind of feel numb, you know.",19.1808,22.8900,sad,3.0,2.0,3.0
3,Session1,Ses01M_impro06.txt,Ses01M_impro06_F001,F001,What's happened?,23.2600,26.3875,neu,3.0,2.0,2.5
4,Session1,Ses01M_impro06.txt,Ses01M_impro06_M002,M002,You didn't even hear?,25.7888,30.0906,sad,2.5,2.0,2.0

In [34]:
# Now you can use df.shape
print("Shape (rows, columns):", df.shape)

Shape (rows, columns): (10087, 11)

In [35]:
print("Total rows:",df.shape[0])

Total rows: 10087

In [36]:
print("Total columns:", df.shape[1])

Total columns: 11

In [37]:
print("\nColumn names and data types:")
print(df.dtypes)

Column names and data types:
session          object
file_name        object
utterance_id     object
speaker          object
utterance        object
start_time      float64
end_time        float64
emotion          object
valence         float64
arousal         float64
dominance       float64
dtype: object

In [38]:
print("\nGeneral info:")
df.info()

General info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10087 entries, 0 to 10086
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   session       10087 non-null  object
 1   file_name     10087 non-null  object
 2   utterance_id  10087 non-null  object
 3   speaker       10087 non-null  object
 4   utterance     10087 non-null  object
 5   start_time    10087 non-null  float64
 6   end_time      10087 non-null  float64
 7   emotion       10039 non-null  object
 8   valence       10039 non-null  float64
 9   arousal       10039 non-null  float64
 10  dominance     10039 non-null  float64
dtypes: float64(5), object(6)
memory usage: 867.0+ KB

In [39]:
print("\nFirst 5 rows:")
display(df.head())

First 5 rows:

,session,file_name,utterance_id,speaker,utterance,start_time,end_time,emotion,valence,arousal,dominance
0,Session1,Ses01M_impro06.txt,Ses01M_impro06_F000,F000,You okay?,10.0955,12.6800,neu,3.0,2.5,2.0
1,Session1,Ses01M_impro06.txt,Ses01M_impro06_M000,M000,"Yeah, I'm just-- yeah",12.4633,16.5100,sad,3.0,2.5,2.0
2,Session1,Ses01M_impro06.txt,Ses01M_impro06_M001,M001,"Just kind of feel numb, you know.",19.1808,22.8900,sad,3.0,2.0,3.0
3,Session1,Ses01M_impro06.txt,Ses01M_impro06_F001,F001,What's happened?,23.2600,26.3875,neu,3.0,2.0,2.5
4,Session1,Ses01M_impro06.txt,Ses01M_impro06_M002,M002,You didn't even hear?,25.7888,30.0906,sad,2.5,2.0,2.0

In [40]:
print("\nLast 5 rows:")
display(df.tail())

Last 5 rows:

,session,file_name,utterance_id,speaker,utterance,start_time,end_time,emotion,valence,arousal,dominance
10082,Session5,Ses05M_impro01.txt,Ses05M_impro01_M020,M020,That's just dumb.,143.25,144.97,fru,1.5,3.5,4.0
10083,Session5,Ses05M_impro01.txt,Ses05M_impro01_F022,F022,But you filled out the wrong form and you're i...,142.93,147.77,fru,2.0,3.5,4.0
10084,Session5,Ses05M_impro01.txt,Ses05M_impro01_M021,M021,I filled out the wrong form because they made ...,145.77,148.79,fru,1.5,4.5,4.5
10085,Session5,Ses05M_impro01.txt,Ses05M_impro01_F023,F023,"Well, that's unfortunate, sir. You're gonna h...",148.43,152.75,ang,2.0,3.5,4.5
10086,Session5,Ses05M_impro01.txt,Ses05M_impro01_M022,M022,"This is crap. You know, I don't even know why...",152.31,160.32,fru,1.5,3.5,4.0

In [41]:
print("\nRandom sample of 5 rows:")
display(df.sample(5))

Random sample of 5 rows:

,session,file_name,utterance_id,speaker,utterance,start_time,end_time,emotion,valence,arousal,dominance
6294,Session4,Ses04F_impro04.txt,Ses04F_impro04_M017,M017,"'Cause if you've been looking, you've been app...",141.9100,147.7700,neu,3.0,2.5,3.5
7245,Session4,Ses04F_impro07.txt,Ses04F_impro07_F074,F074,"Oh, oh, I'm sorry, my bad. I'll have to, like...",366.8700,377.0500,exc,4.5,4.0,4.5
539,Session1,Ses01M_script03_1.txt,Ses01M_script03_1_M034,M034,The one when you put that little wooden painte...,225.5100,230.3900,xxx,3.5,3.5,3.0
6650,Session4,Ses04F_script01_1.txt,Ses04F_script01_1_M017,M017,I'm going to ask her to marry me.,141.3158,144.5575,neu,3.0,2.5,3.5
2537,Session2,Ses02M_script03_2.txt,Ses02M_script03_2_M010,M010,I have a little I think.,55.2122,57.5821,neu,3.0,3.0,2.5

In [43]:
# Unique value counts for key categorical columns
print("Unique sessions:", df['session'].nunique(), "->", sorted(df['session'].unique()))
print("Unique emotions:", df['emotion'].nunique(), "->", df['emotion'].unique())
print("Unique speakers/genders:", df['speaker'].unique())

print("\nTotal unique utterances:", df['utterance_id'].nunique())
print("Total unique dialog files:", df['file_name'].nunique())

# How many rows have no emotion label (didn't match during merge)
print("\nRows with missing emotion label:", df['emotion'].isna().sum())

Unique sessions: 5 -> ['Session1', 'Session2', 'Session3', 'Session4', 'Session5']
Unique emotions: 11 -> ['neu' 'sad' 'xxx' 'exc' 'fru' 'sur' 'ang' 'hap' 'oth' 'fea' 'dis' nan]
Unique speakers/genders: ['F000' 'M000' 'M001' 'F001' 'M002' 'M003' 'M004' 'F002' 'M005' 'M006'
 'F003' 'M007' 'F004' 'F005' 'M008' 'F006' 'M009' 'M010' 'F007' 'M011'
 'F008' 'M012' 'F009' 'M013' 'F010' 'M014' 'F011' 'M015' 'F012' 'M016'
 'F013' 'M017' 'F014' 'F015' 'F016' 'F017' 'M018' 'F018' 'M019' 'F019'
 'M020' 'M021' 'F020' 'M022' 'F021' 'M023' 'F022' 'M024' 'F023' 'F024'
 'M025' 'M026' 'F025' 'M027' 'F026' 'M028' 'M029' 'F027' 'M030' 'F028'
 'M031' 'M032' 'M033' 'M034' 'M035' 'M036' 'M037' 'M038' 'M039' 'M040'
 'M041' 'M042' 'M043' 'M044' 'F029' 'F030' 'F031' 'F032' 'F033' 'F034'
 'F035' 'F036' 'F037' 'F038' 'F039' 'F040' 'F041' 'F042' 'F043' 'M045'
 'F044' 'M046' 'M047' 'F045' 'F046' 'M048' 'F047' 'M049' 'M050' 'M051'
 'M052' 'M053' 'M054' 'FXX0' 'FXX1' 'MXX0' 'FXX2' 'MXX1' 'F048' 'F049'
 'F050' 'F051' 'F052' 'F053' 'MXX2' 'MXX3' 'M055' 'M056' 'F054' 'M057'
 'F055' 'M058' 'F056' 'M059' 'F057' 'M060' 'M061' 'F058' 'M062' 'F059'
 'M063' 'F060' 'M064' 'F061' 'M065' 'F062' 'M066' 'F063' 'M067' 'F064'
 'M068' 'M069' 'F065' 'M070' 'F066' 'M071' 'F067' 'F068' 'M072' 'F069'
 'M073' 'M074' 'F070' 'M075' 'F071' 'M076' 'M077' 'F072' 'M078' 'F073'
 'M079' 'F074' 'M080' 'M081' 'F075' 'M082' 'F076' 'M083' 'F077' 'M084'
 'F078' 'M085' 'F079' 'M086' 'FXX3']

Total unique utterances: 10085
Total unique dialog files: 151

Rows with missing emotion label: 48

summary statistics

In [45]:
# Automatic summary stats for all numeric columns
print("Descriptive statistics (numeric columns):")
display(df.describe())

Descriptive statistics (numeric columns):

         start_time      end_time       valence       arousal     dominance
count  10087.000000  10087.000000  10039.000000  10039.000000  10039.000000
mean     143.529897    147.973124      2.778066      3.089750      3.194326
std      100.167372    100.500630      0.897311      0.701749      0.789100
min        0.462100      3.002500      1.000000      1.000000      0.500000
25%       62.319550     66.915700      2.000000      2.500000      2.500000
50%      127.415000    132.447500      2.500000      3.000000      3.000000
75%      205.352800    209.292800      3.500000      3.500000      4.000000
max      539.575800    542.269100      5.500000      5.000000      5.000000

In [44]:
# Adding variance explicitly (describe() doesn't include it by default)
print("\nVariance per numeric column:")
print(df[['start_time', 'end_time', 'valence', 'arousal', 'dominance']].var())

Variance per numeric column:
start_time    10033.502423
end_time      10100.376625
valence           0.805167
arousal           0.492452
dominance         0.622678
dtype: float64

In [47]:
# Manually compute mean, median, mode, std, variance, quartiles per numeric column
numeric_cols = ['start_time', 'end_time', 'valence', 'arousal', 'dominance']

for col in numeric_cols:
    print(f"\n--- {col} ---")
    print("Mean:", df[col].mean())
    print("Median:", df[col].median())
    print("Mode:", df[col].mode()[0])
    print("Variance:", df[col].var())
    print("Std Dev:", df[col].std())
    print("Q1 (25%):", df[col].quantile(0.25))
    print("Q2 (50% / median):", df[col].quantile(0.50))
    print("Q3 (75%):", df[col].quantile(0.75))
    print("IQR:", df[col].quantile(0.75) - df[col].quantile(0.25))

--- start_time ---
Mean: 143.52989669872113
Median: 127.415
Mode: 81.52
Variance: 10033.50242279199
Std Dev: 100.16737204694945
Q1 (25%): 62.31955000000001
Q2 (50% / median): 127.415
Q3 (75%): 205.3528
IQR: 143.03325

--- end_time ---
Mean: 147.97312366412214
Median: 132.4475
Mode: 35.79
Variance: 10100.37662453422
Std Dev: 100.50062997083262
Q1 (25%): 66.9157
Q2 (50% / median): 132.4475
Q3 (75%): 209.2928
IQR: 142.37709999999998

--- valence ---
Mean: 2.778065524454627
Median: 2.5
Mode: 2.0
Variance: 0.8051669224007706
Std Dev: 0.8973109396417557
Q1 (25%): 2.0
Q2 (50% / median): 2.5
Q3 (75%): 3.5
IQR: 1.5

--- arousal ---
Mean: 3.089749875485606
Median: 3.0
Mode: 3.0
Variance: 0.4924518792585972
Std Dev: 0.701749156934725
Q1 (25%): 2.5
Q2 (50% / median): 3.0
Q3 (75%): 3.5
IQR: 1.0

--- dominance ---
Mean: 3.1943255005478632
Median: 3.0
Mode: 3.0
Variance: 0.622678368769865
Std Dev: 0.7890997204218647
Q1 (25%): 2.5
Q2 (50% / median): 3.0
Q3 (75%): 4.0
IQR: 1.5